[book]
title = "安防監控系統(樹莓派版)"
authors = ["guy.mai"]
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"
optional = true

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js", "assets/fzf.umd.js", "assets/elasticlunr.js"]